name: test_flutter
description: "A flute quickboot reusable template project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  fluteqboot:
    path: fluteqboot

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.8.0+1
  drift: 2.23.1
  drift_flutter: 0.2.4
  beamer: ^1.7.0  
  flutter_svg: ^2.0.17
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: 2.23.1
  build_runner: 2.4.13

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/ic_back.svg
    - assets/icons/ic_filter.svg
    - assets/icons/ic_search.svg
    - assets/icons/ic_home.svg
    - assets/icons/ic_shop.svg
    - assets/icons/ic_notif.svg
    - assets/icons/ic_heart.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
