name: fluteqboot
description: "A flute quickboot reusable module"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.nokotogi.fluteqboot
    iosBundleIdentifier: com.nokotogi.fluteqboot
